name: release package

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test


    - name: Extract tag name
      id: extract_tag
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        fi

    - name: Display tag name
      if: env.TAG_NAME != ''
      run: 
        run: echo "The name is ${{ env.TAG_NAME }}"
