name: release package

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test


    - name: Extract tag name
      id: extract_tag
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        fi

    - name: get changeset type
      id: determine_changeset
      run: |
        if [[ "${{ env.TAG_NAME }}" == patch-* ]]; then
          echo "CHANGESET_TYPE=patch" >> $GITHUB_ENV
        elif [[ "${{ env.TAG_NAME }}" == minor-* ]]; then
          echo "CHANGESET_TYPE=minor" >> $GITHUB_ENV
        elif [[ "${{ env.TAG_NAME }}" == major-* ]]; then
          echo "CHANGESET_TYPE=major" >> $GITHUB_ENV
        else
          echo "CHANGESET_TYPE=custom" >> $GITHUB_ENV
        fi

    - name: console
      if: env.TAG_NAME != ''
      run: 
        run: echo "The type is ${{ env.CHANGESET_TYPE }} and ${{ env.TAG_NAME }} "

    #  - name: Generate changeset
    #   if: env.TAG_NAME != ''
    #   run: |
    #     echo "Generating changeset for tag ${{ env.TAG_NAME }}"